# Site settings
title: Andrew Fiorillo
short_title: AM Fiorillo
name: Andrew Fiorillo
email: andrewmfiorillo@gmail.com
repository: andrewmfiorillo/andrewmfiorillo.github.io
meta_description: A selected "telefolio."
description: >
  I live in the summertime paradise of Berlin (Germany).
  I work like a madman, bake like a madman, and travel like a madman.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andrewmfiorillo.github.io"
twitter_username: muthebeagle
github_username:  andrewmfiorillo
linkedin_username: andrewmfiorillo
resume_href: "/docs/fiorillo_resume.pdf"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
