title: "Andrew Fiorillo"
description: "I'm a software engineer with a passion for physics and mathematics."
about: "I've been working in computer vision, database design, and HPC solutions.<br>
My education has been focused on Physics and Mathematics.<br>
I spend my off hours learning new laguages and tinkering.<br>"
# info-text: ""
location: "Tampa, Florida"
email: andrewmfiorillo@gmail.com
baseurl: ""
url: "https://andrewmfiorillo.github.io/" # replace by your site's url
resume_link: FiorilloAndrew.pdf
linkedin_username: andrewmfiorillo
twitter_username: muthebeagle
github_username:  andrewmfiorillo

# google analytics tracking code, please change the value
g_analytics: "UA-81332412-1"

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
# about_btn: "Info"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# exclude files
exclude:
  - LICENSE
  - README.md
